version: 2.1

workflows:
   ui-deploy: 
      jobs:
        - makeUI

jobs:
  makeUI:
    docker:
     - image: circleci/node:14.20.0-browsers
    
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
             - node_modules
             - ~/.npm
             - ~/.cache
      - run: npm run build
     
      - setup_remote_docker
      - run: |
          docker build . -t $REPONAME
      # - run: |
      #     if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
      #     TAG=$CIRCLE_TAG
      #     echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #     REPONAME = $CIRCLE_PROJECT_REPONAME
      #     docker build . -t $DOCKER_USER/$REPONAME:$TAG
      #     #docker tag $REPONAME:latest $DOCKER_USER/$REPONAME:$TAG
      #     #docker push $DOCKER_USER/$REPONAME:$TAG
      
