module.exports = {
  CASE_EVENT: "/case/event",
  CASE_DEFINITION: "/case-definition",
  CASE_INSTANCE: "/case-instance",
  HISTORY_CASE_INSTANCE: "/history/case-instance",
  CONVERSATION_HISTORY: "/chat/history/working/",
  WORKFLOW_FILTER: "/workflow/v1/filter",
  WORKFLOW_COMMENTS: "/workflow/v1/comments?businessKey=",
  WORKFLOW: "/workflow/v1",
  FILTER: "/filter",
  TASK: "/task",
  CONFIG: "/dashboard/config",
  CASE_EXECUTION: "/case-execution",
  CASE_ACTIVITI_TASKS: "/history/case-activity-instance?caseInstanceId=",
  RUNTIME_FORM: "/form-runtime/v1/forms/",
  FORM_VARIABLES: "/form-variables",
  SUBMIT_TASK: "/workflow/v1/tasks/complete",
  CASE_COMMENTS: "/workflow/v1/comments",
  PREFERENCE_ENDPOINT: "/accounts/v1/users/preferences",
  THEME_ENDPOINT: "/accounts/v1/themes",
  CHECKLIST_INSTANCE: "/checklist-engine/v1/checklist-instances",
  CHECKLIST_ITEM_INSTANCE: "/checklist-engine/v1/checklist-item-instances",
  DATA_TABLE_HEADERS: [
    { id: "name", label: "Name", disableSorting: true },
    { id: "description", label: "Description", disableSorting: true },
    { id: "createdOn", label: "Created Date", disableSorting: false },
    { id: "createdBy", label: "Created By", disableSorting: false },
  ],
};
